### ISSUE TITLE
should not error when there are no peer dependencies; just quietly install the package and move on

### ISSUE THREAD

**Issue by jeffory-orrok** [nathanhleung/install-peerdeps#144] opened 2021-04-17 23:11 UTC
This should not happen
```
install-peerdeps -g @apidevtools/swagger-cli
install-peerdeps v3.0.3
(node:70794) UnhandledPromiseRejectionWarning: Error: The package you are trying to install has no peer dependencies. Use yarn or npm to install it manually.
    at /Users/jeff/.nvm/versions/node/v12.20.0/lib/node_modules/install-peerdeps/lib/install-peerdeps.js:248:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:70794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:70794) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ljharb** [comment] 2021-04-17 23:18
Seems like a duplicate of #142.

**Comment by jeffory-orrok** [comment] 2021-04-17 23:23
@ljharb I suppose at the heart of it, it is.  But I don't usually read every open issue in depth before deciding whether to create a new issue.

**Comment by nathanhleung** [comment] 2021-08-03 23:30
Closing as duplicate of #142

**Closed by nathanhleung** 2021-08-03 23:30 UTC
